"""Tool garbage collector.

Periodically reviews probationary tools (those generated by `create_tool`)
and archives ones that haven't earned their keep:

  * Never used + age > `prune_after_days` (default 7) → archive + unregister.
  * Low usage (< 3 calls) + age > 30 days → flag for human review.

Archive moves the source file from `vault/_kee/tools/<name>.py` to
`vault/_kee/tools/archive/<name>_<stamp>.py`. The tool is unregistered
in-memory; the SQLite row is preserved as a record.

Phase 0 builds the daemon but `main.py` only spawns it for surfaces that
run long enough to make GC meaningful (a single REPL session is too short).
"""

from __future__ import annotations

import asyncio
import logging
import shutil
from datetime import datetime
from pathlib import Path

from kee.config import settings
from kee.core import services
from kee.core.tool_registry import ToolRegistry

logger = logging.getLogger(__name__)


class ToolGarbageCollector:
    def __init__(
        self,
        registry: ToolRegistry,
        prune_after_days: float = 7.0,
        flag_after_days: float = 30.0,
        interval_s: int = 3600,
    ) -> None:
        self.registry = registry
        self.prune_after_days = prune_after_days
        self.flag_after_days = flag_after_days
        self.interval_s = interval_s
        self._stop = asyncio.Event()

    def stop(self) -> None:
        self._stop.set()

    async def run_forever(self) -> None:
        logger.info(
            "Tool GC running (prune=%.1fd, flag=%.1fd, interval=%ds)",
            self.prune_after_days, self.flag_after_days, self.interval_s,
        )
        while not self._stop.is_set():
            try:
                self.sweep_once()
            except Exception:
                logger.exception("Tool GC sweep failed")
            try:
                await asyncio.wait_for(self._stop.wait(), timeout=self.interval_s)
            except asyncio.TimeoutError:
                pass

    def sweep_once(self) -> dict[str, int]:
        archived = 0
        flagged = 0
        for entry in self.registry.get_probationary_tools():
            age = entry["age_days"]
            uses = entry["use_count"]
            last_used = entry["last_used"]

            if uses == 0 and age > self.prune_after_days:
                self._archive(entry["name"], entry.get("file_path"))
                archived += 1
            elif uses < 3 and age > self.flag_after_days and last_used is None:
                logger.info(
                    "Tool '%s' used %d× in %.0f days — candidate for review.",
                    entry["name"], uses, age,
                )
                if services.audit:
                    services.audit.log_event("tool_flagged_low_use", entry)
                flagged += 1
        return {"archived": archived, "flagged": flagged}

    def _archive(self, name: str, file_path: str | None) -> None:
        if file_path:
            src = Path(file_path)
            if src.exists():
                archive_dir = settings.custom_tools_dir / "archive"
                archive_dir.mkdir(exist_ok=True)
                stamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
                dest = archive_dir / f"{src.stem}_{stamp}.py"
                shutil.move(str(src), dest)
                logger.warning("Archived unused probationary tool '%s' → %s", name, dest)
        self.registry.unregister(name)
        if services.audit:
            services.audit.log_event("tool_archived", {"tool_name": name})
