"""Meta-tool: Kee writes its own tools.

When the agent decides no existing tool fits, it can call `create_tool` to
generate a new Python module, sandbox-test it, archive any prior version,
and register it (probationary) for immediate use. The Phase 0 implementation
is full-featured; what's stubbed is only the *Phase 4* notification layer
(WhatsApp / Telegram) — for now we emit a console warning + audit event.

Hardening:
  1. **Sandbox test** — run the candidate code in a separate Python
     interpreter with a 10 s timeout. If it fails to import or throws, we
     refuse to register.
  2. **Versioning** — if a tool of the same name already exists, the previous
     file is moved to `vault/_kee/tools/archive/<name>_<utc>.py` before write.
  3. **Probation** — newly created tools are flagged probationary; the GC
     archives them if unused for 7 days.
  4. **Audit** — every step is recorded.
"""

from __future__ import annotations

import asyncio
import importlib.util
import logging
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

from kee.config import settings
from kee.core import services
from kee.tools.base import Tool

logger = logging.getLogger(__name__)


async def _notify_user(title: str, body: str, kind: str = "info") -> None:
    """Thin wrapper over the shared `kee.perception.notifications.notify_user`
    fan-out. Kept here so create_tool callers don't import perception."""
    from kee.perception.notifications import notify_user
    await notify_user(title=title, body=body, kind=kind)


_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{1,40}$")


def _to_class_name(snake: str) -> str:
    return "".join(part.capitalize() for part in snake.split("_")) + "Tool"


def _wrap(tool_name: str, description: str, parameters_schema: dict, body: str,
          risk_level: int) -> str:
    """Wrap an `execute` body in a fully-formed Tool subclass module."""
    indented = "\n".join("        " + line for line in body.splitlines()) or "        pass"
    schema_repr = repr(parameters_schema)
    return f'''"""Auto-generated by Kee on {datetime.utcnow().isoformat()}Z."""
from typing import Any
from kee.tools.base import Tool


class {_to_class_name(tool_name)}(Tool):
    name = {tool_name!r}
    description = {description!r}
    risk_level = {risk_level}
    source = "kee_generated"
    parameters_schema = {schema_repr}

    async def execute(self, **kwargs: Any):
{indented}


tool = {_to_class_name(tool_name)}()
'''


async def _sandbox_test(full_code: str, timeout_s: int = 10) -> dict[str, Any]:
    """Spawn a subprocess that imports the module to verify it doesn't crash.

    We add the project root to sys.path so the candidate's `from kee.tools.base
    import Tool` resolves. The subprocess prints a sentinel on success.
    """
    sentinel = "KEE_SANDBOX_OK"
    project_root = str(settings.project_root)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir) / "candidate.py"
        tmp.write_text(full_code, encoding="utf-8")

        bootstrap = (
            f"import sys, importlib.util, asyncio\n"
            f"sys.path.insert(0, r'{project_root}')\n"
            f"spec = importlib.util.spec_from_file_location('candidate', r'{tmp}')\n"
            f"m = importlib.util.module_from_spec(spec)\n"
            f"spec.loader.exec_module(m)\n"
            f"assert hasattr(m, 'tool'), 'no tool attribute'\n"
            f"assert callable(getattr(m.tool, 'execute', None)), 'no execute coroutine'\n"
            f"print('{sentinel}')\n"
        )

        try:
            proc = await asyncio.create_subprocess_exec(
                sys.executable, "-c", bootstrap,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout_s)
        except asyncio.TimeoutError:
            return {"passed": False, "error": f"sandbox timed out after {timeout_s}s"}
        except FileNotFoundError as e:
            return {"passed": False, "error": f"interpreter not found: {e}"}

        ok = sentinel in stdout.decode("utf-8", errors="replace")
        return {
            "passed": ok,
            "exit_code": proc.returncode,
            "stdout": stdout.decode("utf-8", errors="replace")[-400:],
            "stderr": stderr.decode("utf-8", errors="replace")[-400:],
        }


class CreateToolTool(Tool):
    name = "create_tool"
    description = (
        "Write a new Python tool, sandbox-test it, archive any prior version, "
        "and register it for immediate use. Use when no existing tool fits the "
        "task. Provide complete, working code for the `execute` body — not the "
        "wrapping class. New tools start probationary and are removed after 7 "
        "days if unused."
    )
    risk_level = 2
    parameters_schema = {
        "type": "object",
        "properties": {
            "tool_name": {
                "type": "string",
                "description": "Snake_case name (^[a-z][a-z0-9_]{1,40}$).",
            },
            "description": {
                "type": "string",
                "description": "What the tool does — written for the LLM caller.",
            },
            "parameters_schema": {
                "type": "object",
                "description": "OpenAI-style JSON Schema for the tool parameters.",
            },
            "code": {
                "type": "string",
                "description": (
                    "Python code for the body of `async def execute(self, **kwargs)`. "
                    "Will be indented and wrapped in a Tool subclass."
                ),
            },
            "risk_level": {
                "type": "integer",
                "description": "0=read, 1=local write, 2=system mutation, 3=external.",
                "default": 1,
            },
        },
        "required": ["tool_name", "description", "parameters_schema", "code"],
    }

    async def execute(
        self,
        tool_name: str,
        description: str,
        parameters_schema: dict,
        code: str,
        risk_level: int = 1,
    ) -> dict[str, Any]:
        # 1. Validate name.
        if not _NAME_RE.match(tool_name):
            return {"status": "rejected", "reason": "invalid tool_name (snake_case, 2-41 chars)"}

        full_code = _wrap(tool_name, description, parameters_schema, code, risk_level)

        # 2. Sandbox.
        sandbox = await _sandbox_test(full_code)
        if not sandbox["passed"]:
            if services.audit:
                services.audit.log_anomaly(
                    tool_name=tool_name,
                    verification={"sandbox": sandbox},
                    kind="sandbox_fail",
                    severity=2,
                )
            return {"status": "rejected", "reason": "sandbox failed", "sandbox": sandbox}

        # 3. Archive previous version.
        tool_dir = settings.custom_tools_dir
        tool_dir.mkdir(parents=True, exist_ok=True)
        tool_path = tool_dir / f"{tool_name}.py"

        if tool_path.exists():
            archive_dir = tool_dir / "archive"
            archive_dir.mkdir(exist_ok=True)
            stamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            shutil.move(str(tool_path), archive_dir / f"{tool_name}_{stamp}.py")

        # 4. Write.
        tool_path.write_text(full_code, encoding="utf-8")

        # 5. Import and register (probationary).
        spec = importlib.util.spec_from_file_location(tool_name, tool_path)
        if spec is None or spec.loader is None:
            return {"status": "error", "reason": "could not build import spec"}

        module = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(module)
        except Exception as e:
            tool_path.unlink(missing_ok=True)
            return {"status": "rejected", "reason": f"import failed: {e}"}

        instance = getattr(module, "tool", None)
        if not isinstance(instance, Tool):
            tool_path.unlink(missing_ok=True)
            return {"status": "rejected", "reason": "module exports no `tool` attribute"}

        instance.file_path = str(tool_path)
        if services.registry is None:
            return {"status": "error", "reason": "registry not bound"}
        services.registry.register(instance, probationary=True)

        # 6. Notify the user — Phase 5 close. Three fan-out channels:
        #    - audit_log (durable, dashboard sees via WS/audit_tailer)
        #    - desktop notification (winotify/notify-send via NotifyTool)
        #    - Telegram message (if KEE_TELEGRAM_TOKEN + ALLOWED_USERS set,
        #      best-effort, non-blocking)
        msg = (
            f"Kee created new tool: {tool_name}. Status: probationary "
            f"(auto-archives after 7 days if unused). Sandbox: passed."
        )
        logger.warning(msg)
        if services.audit:
            services.audit.log_event("tool_created", {
                "tool_name": tool_name,
                "description": description,
                "risk_level": risk_level,
                "file_path": str(tool_path),
            })
        try:
            await _notify_user(
                title=f"🔧 New tool: {tool_name}",
                body=(f"{description[:120]}\n"
                      f"Risk r{risk_level} · probationary 7d"),
                kind="tool_created",
            )
        except Exception as e:
            logger.warning("create_tool notification failed: %s", e)

        return {
            "status": "created",
            "probationary": True,
            "file_path": str(tool_path),
            "sandbox": {"passed": True},
            "notification": msg,
        }


tool = CreateToolTool()
