# Install a desktop + Start Menu shortcut for Kee.
#
#   - "Kee.lnk" on the Desktop (or OneDrive\Escritorio if OneDrive is hijacking)
#   - "Kee.lnk" under %APPDATA%\Microsoft\Windows\Start Menu\Programs\
#
# Target: powershell.exe (hidden) running scripts\launch_kee_app.ps1, which
# brings up Ollama + Kee API + opens the dashboard in app-mode.
#
# Icon: assets\kee.ico (generated by scripts\build_icon.py).
#
# Idempotent — overwrites previous shortcuts of the same name.

$ErrorActionPreference = 'Stop'

$KeeRoot     = 'D:\Kee'
$LauncherPS1 = Join-Path $KeeRoot 'scripts\launch_kee_app.ps1'
$IconPath    = Join-Path $KeeRoot 'assets\kee.ico'

if (-not (Test-Path $LauncherPS1)) {
    throw "Launcher not found: $LauncherPS1 (run from D:\Kee)."
}
if (-not (Test-Path $IconPath)) {
    Write-Warning "Icon not found: $IconPath. Run scripts\build_icon.py first."
}

# ── Candidate target directories ────────────────────────────────────────
$desktops = @()
$localDesktop = [Environment]::GetFolderPath('Desktop')
if ($localDesktop) { $desktops += $localDesktop }
# OneDrive can rebase the Desktop folder.
$onedrive = $env:OneDrive
if ($onedrive) {
    foreach ($name in @('Desktop','Escritorio')) {
        $p = Join-Path $onedrive $name
        if ((Test-Path $p) -and ($desktops -notcontains $p)) { $desktops += $p }
    }
}

$startMenu = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'

$targets = $desktops + @($startMenu) | Where-Object { Test-Path $_ } |
    Select-Object -Unique

# ── Build .lnk in each target ───────────────────────────────────────────
$shell = New-Object -ComObject WScript.Shell

foreach ($dir in $targets) {
    $lnkPath = Join-Path $dir 'Kee.lnk'
    $lnk = $shell.CreateShortcut($lnkPath)
    $lnk.TargetPath = 'powershell.exe'
    # -WindowStyle Hidden hides the powershell host completely.
    # -ExecutionPolicy Bypass so the user doesn't need to flip it globally.
    $lnk.Arguments = "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$LauncherPS1`""
    $lnk.WorkingDirectory = $KeeRoot
    $lnk.WindowStyle = 7   # 7 = Minimized (suppresses the brief ps host flash)
    $lnk.Description = 'Kee — sovereign personal AI agent'
    if (Test-Path $IconPath) {
        $lnk.IconLocation = "$IconPath,0"
    }
    $lnk.Save()
    Write-Host "Installed: $lnkPath"
}

# Also remove Codex's old "Kee Chat.lnk" if it exists alongside ours — that
# one only opened the REPL and is superseded by Kee.lnk.
foreach ($dir in $desktops) {
    $old = Join-Path $dir 'Kee Chat.lnk'
    if (Test-Path $old) {
        Remove-Item $old -Force
        Write-Host "Removed legacy shortcut: $old"
    }
}

Write-Host ""
Write-Host "Done. Double-click Kee from the Desktop or Start Menu to launch."
